server:
  port: 9090
#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.cloud.gateway: DEBUG

spring:
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: survey-service
          uri: lb://survey-service
          predicates:
            - Path=/api/survey/**
        - id: answer-service
          uri: lb://answer-service
          predicates:
            - Path=/api/answer/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
