server:
  port: 8761
#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework.web.HttpLogging: DEBUG
#    org.springframework.security: DEBUG
#    org.springframework.security.oauth2: DEBUG
#    org.springframework.cloud.gateway: DEBUG
#    org.springframework.cloud.netflix.eureka: DEBUG

spring:
  application:
    name: discovery-service

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka
